<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="test_vaccine_patient_tests.TestVaccinePatient-20220523112427" tests="6" file="test_vaccine_patient_tests.py" time="0.121" timestamp="2022-05-23T11:24:30" failures="0" errors="0" skipped="1">
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_bad_date_signature" time="0.030" timestamp="2022-05-23T11:24:30"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_no_date" time="0.030" timestamp="2022-05-23T11:24:30"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_not_found_date_signature" time="0.020" timestamp="2022-05-23T11:24:30"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_ok" time="0.020" timestamp="2022-05-23T11:24:30"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_store_date_is_empty" time="0.021" timestamp="2022-05-23T11:24:30"/>
	<testcase classname="test_vaccine_patient_tests.TestVaccinePatient" name="test_vaccine_patient_no_store_date" time="0.000" timestamp="2022-05-23T11:24:30">
		<skipped cancellation_type="skip" message="This exception won't be raised after the refactoring process"/>
	</testcase>
</testsuite>
